import type { ExtractionResult } from "./extract.functions";

const SECTIONS: Array<{
  key: keyof ExtractionResult;
  heading: string;
  category: string;
}> = [
  { key: "people", heading: "Names of People &amp; Peoples", category: "Names" },
  { key: "topics", heading: "Topics + Casenames", category: "Topics" },
  {
    key: "organisations",
    heading: "Names of Organisations and Vessels",
    category: "Organisations",
  },
  {
    key: "science",
    heading: "Scientific, Medical &amp; Technical",
    category: "Scientific",
  },
  {
    key: "fictional",
    heading: "Names (Legendary and Fictional)",
    category: "Fictive/Legendary",
  },
  { key: "places", heading: "Places", category: "Places" },
  { key: "dates", heading: "Dates", category: "Dates" },
  { key: "filmsTV", heading: "Films &amp; TV", category: "Films &amp; TV" },
  {
    key: "letters",
    heading: "Letters &amp; It Happened To Me",
    category: "Letters &amp; IHTM",
  },
  { key: "reviews", heading: "Reviews", category: "Reviews" },
];

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function buildIndexHtml(
  result: ExtractionResult,
  pageLabel: string,
): string {
  const title = `Fortean Times — ${esc(pageLabel || "Structured Index")}`;

  const body = SECTIONS.map((section) => {
    const items = result[section.key];
    if (!items || items.length === 0) return "";
    const rows = [...items]
      .sort((a, b) => a.text.localeCompare(b.text, "en"))
      .map((item) => {
        const where = item.page ? `p${esc(item.page)}` : pageLabel ? esc(pageLabel) : "";
        const detail = [where, esc(item.reason || item.context || "")]
          .filter(Boolean)
          .join(" — ");
        return `<tr><td>${esc(item.text)}</td><td>${section.category}</td><td>${detail}</td></tr>`;
      })
      .join("\n");
    return `<!-- ═══════════════════ ${section.category.toUpperCase()} ═══════════════════ -->
<h2>${section.heading}</h2>
<table>
<tr><th>Entry Name</th><th>Category</th><th>Page / Section</th></tr>

${rows}
</table>
`;
  })
    .filter(Boolean)
    .join("\n\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${title} — Structured Index</title>
<style>
  body { font-family: Georgia, serif; margin: 2em 3em; font-size: 14px; color: #111; }
  h1 { font-size: 1.5em; margin-bottom: 0.2em; }
  h2 { font-size: 1.15em; margin-top: 2em; border-bottom: 2px solid #444; padding-bottom: 0.2em; color: #2c2c6c; }
  p.subtitle { color: #555; font-style: italic; margin-top: 0; }
  table { border-collapse: collapse; width: 100%; margin-top: 0.8em; }
  th { background: #2c2c6c; color: #fff; padding: 7px 10px; text-align: left; font-size: 0.95em; }
  tr:nth-child(even) { background: #f2f2f8; }
  td { padding: 5px 10px; vertical-align: top; border-bottom: 1px solid #ddd; }
  td:first-child { width: 32%; font-weight: bold; }
  td:nth-child(2) { width: 18%; color: #555; font-style: italic; }
  td:last-child { width: 50%; }
  .note { font-size: 0.85em; color: #666; margin-top: 2em; }
</style>
</head>
<body>

<h1>${title}</h1>
<p class="subtitle">Structured Index compiled with the FT Indexing Assistant &nbsp;|&nbsp; Entries alphabetical within category &nbsp;|&nbsp; Advertisements excluded</p>

${body}

<p class="note">Generated by the Fortean Times Indexing Assistant. Reviewed and edited by a human indexer.</p>

</body>
</html>
`;
}

export function buildHtmlBlob(
  result: ExtractionResult,
  pageLabel: string,
): Blob {
  return new Blob([buildIndexHtml(result, pageLabel)], {
    type: "text/html;charset=utf-8",
  });
}
